name: fitting_room
description: Fitting Room frontend.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter
  package_info: 0.4.3+4
  intl: ^0.16.1
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  path_provider: 1.6.27
  http: ^0.12.2
  json_annotation: ^3.1.1
  scan: ^0.0.7
  geolocator: 6.2.1
  image_picker: 0.6.7+22
  image_cropper: ^1.3.1
  cached_network_image: ^2.5.0
  flutter_cache_manager: 2.1.1
  flutter_swiper: ^1.1.6
  photo_view: 0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  build_runner: 1.10.2
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - asset/avatar.png
  fonts:
    - family: frIcon
      fonts:
        - asset: font/icon.ttf
